name: goindia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  awesome_bottom_bar: ^1.2.4
  gap: ^3.0.1
  flutter_rating_bar: ^4.0.1
  dio: ^5.8.0+1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  geolocator: ^13.0.2
  shared_preferences: ^2.5.2
  stacked: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
